AliProject/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from Alisystem.views import *
from django.contrib.auth.views import LoginView, LogoutView
from Alisystem.forms import BootstrapAuthenticationForm, RegistrarPagamentosForm

urlpatterns = [
    path('admin/', admin.site.urls),

    # Telas básicas
    path('', home, name='home'),
    #path(r'^contact$', contact, name='contact'),
    #path(r'^about', about, name='about'),

   # Login e logout
    url(r'^login/$', LoginView.as_view(template_name='app/login.html'), name='login'),
    url(r'^logout$', LogoutView.as_view(next_page='/'), name='logout'),

   # MÓDULO INSERIR ATENDIMENTOS
    url(r'^inserir_atendimentos/$', AtendimentosProcedimentos_aplicadoCreate.as_view(), name='inserir_atendimentos'),

   # MÓDULO PAGAMENTOS
	url(r'^pagamentos/$', mostra_pagamentos, name="pagamentos"),
    url(r'^pagamentos/data_repasse/$', atribui_data_repasse),
	url(r'^pagamentos/data_repasse/confirma/$', confirma_data_repasse),
    url(r'^pagamentos/data_repasse/confirma/atualiza$', atualiza_valores),
    url(r'^registrar_pagamentos/$', registrar_pagamentos, name="registrar_pagamentos"),
    url(r'^registrar_pagamentos/apresenta$', registrar_pagamentos, name="registrar_pagamentos"),
    url(r'^contact/thanks$', contact_thanks),

    # MÓDULO PAINÉIS
    url(r'^dentistas/$', DentistaList.as_view(), name='dentistas'),
    url(r'^atendimentos/dentista/([\w-]+)/$', AtendimentoDentistaList.as_view()),
    url(r'^atendimentos/$', AtendimentoList.as_view(), name='atendimentos'),
    url(r'^atendimentos/(?P<pk>[0-9]+)/$', ProcedimentoAtendimentoList.as_view(), name = 'atendimento_list'),
    url(r'^atendimentos/dentista/([\w-]+)/(?P<pk>[0-9]+)/$', ProcedimentoAtendimentoList.as_view()),
    url(r'^procedimentos/dentista/([\w-]+)/$', Procedimentos_aplicadoDentistaDataList.as_view()),
    url(r'^procedimentos/dentista/([\w-]+)/glosado/$', AtendimentoDentistaGlosadoList.as_view()),

]

Alisystem/models.py
# Alisystem_GTO Experiência de colocar vários procedimentos na mesma GTO

from django.db import models
#from django.core.urlresolvers import reverse # Para possibilitar a manipulação de dados com forms - Obsoleto a partir do Django 2
from django.urls import reverse


# Create your models here.

class Convenio(models.Model):
    convenio = models.CharField(max_length=40)

    def get_absolute_url(self):	# Para possibilitar a manipulação de dados com forms
    	return reverse('convenio_list') #, kwargs={'pk': self.pk})

    def __str__(self): # Ordenação por 'convenio'
        return self.convenio
    class Meta:	ordering = ['convenio']



class Paciente(models.Model):
    nome_completo = models.CharField(max_length=100)
    nome_responsavel = models.CharField(max_length=100, blank = True, verbose_name = 'Nome do responsável')
#   convenio = models.ForeignKey(Convenio)
    data_nascimento = models.DateField(blank = True, null = True, verbose_name = 'Data de nascimento')
    email = models.EmailField(blank = True, verbose_name = 'e-mail')

    def __str__(self):
        return self.nome_completo
    class Meta: ordering = ['nome_completo']

class Formas_pagamento(models.Model):
    forma_pagamento = models.CharField(max_length=30, verbose_name = 'Forma de pagamento')
    comissao = models.FloatField(blank=True, null=True, verbose_name = 'Comissão/ impostos (%)', help_text='Registre aqui o valor da comissão dos meios de pagamento ou da alíquota de impostos')
    taxa_fixa = models.FloatField(blank=True, null=True, verbose_name = 'Taxa Fixa (R$)')

    def __str__(self):
        return self.forma_pagamento

class Dentista(models.Model):
    nome_completo = models.CharField(max_length=100)
    num_CRO = models.CharField(max_length=100, blank = True, verbose_name = 'Número do CRO')
    email = models.EmailField(blank = True, verbose_name = 'E-mail')
    cpf = models.CharField(max_length=11, blank = True)
    banco = models.CharField(max_length=30, blank = True)
    num_agencia = models.CharField(max_length=4, blank = True, verbose_name = 'Agência número')
    num_conta = models.CharField(max_length=20, blank = True, verbose_name = 'Conta número')

    def __str__(self):
        return self.nome_completo
    class Meta: ordering = ['nome_completo']

class Tipos_procedimento(models.Model):
	tipo_procedimento = models.CharField(max_length=30, blank = True, verbose_name = 'Tipo do procedimento')

	def __str__(self):
		return self.tipo_procedimento

class Procedimento(models.Model):
    procedimento = models.CharField(max_length=100)
    tipo_procedimento = models.ForeignKey(Tipos_procedimento, blank = True, null = True, verbose_name = 'Tipo do procedimento', on_delete=models.CASCADE)
    tabela_preço = models.FloatField(blank=True, null=True, verbose_name = 'Tabela de preço')

    def __str__(self):
        return self.procedimento
    class Meta: ordering = ['procedimento']

class Tabela_preco(models.Model):
    procedimento = models.ForeignKey(Procedimento, on_delete=models.CASCADE)
    convenio = models.ForeignKey(Convenio, on_delete=models.CASCADE)
    preco = models.FloatField(blank=True, null=True, verbose_name = 'Preço')


#    def __str__(self):
#       return self.procedimento
    class Meta: ordering = ['procedimento']

class Encaminhamento(models.Model):
	descricao = models.CharField(max_length = 200, blank=True)
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
	dentista = models.ForeignKey(Dentista, on_delete=models.CASCADE)
	data_encaminhamento = models.DateField(verbose_name = 'Data do encaminhamento')

	def __str__(self):
		return self.descricao

	class Meta:
		ordering = ['paciente']

## Tabela Atendimento contém a GTO
class Atendimento(models.Model):
	dentista = models.ForeignKey(Dentista, on_delete=models.CASCADE)
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
	convenio = models.ForeignKey(Convenio, null=True, on_delete=models.CASCADE)
	forma_pagamento = models.ForeignKey(Formas_pagamento, blank=True, null=True, verbose_name = 'Forma de pagamento', on_delete=models.CASCADE)
	data_atendimento = models.DateField(blank=True, null=True, verbose_name = 'Data do atendimento')
	num_GTO = models.CharField(max_length = 30, null=True, blank = True, verbose_name = 'Número da GTO')
#	procedimentos_aplicados = models.ManyToManyField(Procedimentos_aplicado)
	data_envio = models.DateField(blank=True, null=True, verbose_name = 'Data de envio')
	mes_recebimento = models.DateField(blank=True, null=True, verbose_name = 'Mês de recebimento')
	comentarios = models.CharField(max_length = 500, blank=True, verbose_name = 'Comentários')
#	encaminhamento = models.ForeignKey(Encaminhamento, blank=True, null=True, help_text="Registre novos encaminhamentos aqui")
	encaminhado_por = models.CharField(max_length = 30, blank=True, verbose_name = 'Encaminhado por', help_text='Registrar nome do dentista ou funcionário que encaminhou o paciente')
	verificado = models.BooleanField(blank=True, default=False, verbose_name = 'Atendimento verificado', help_text='Atendimento verificado pela administração do consultório')

#	def valor_GTO(self):
#		valor_GTO =

	def get_absolute_url(self):
		return reverse('atendimento_list', kwargs={'pk': self.pk})

	def __str__(self):
		dentista = self.dentista
		convenio = self.convenio
		paciente = self.paciente
		atendimento = dentista.nome_completo + "/ " + convenio.convenio + "/ " + paciente.nome_completo
		return atendimento

	class Meta:
		ordering = ['-data_atendimento']



## Tabela Procedimentos_aplicado, em relacionamento 1-muitos com Atendimento (que contém a GTO)
## Cada Atendimento (GTO), contém vários Procedimentos_aplicados
class Procedimentos_aplicado(models.Model):
	atendimento = models.ForeignKey(Atendimento, blank=True, null=True, on_delete=models.CASCADE)
	procedimento = models.ForeignKey(Procedimento, blank=True, null=True, help_text='Escolha o seu procedimento nesta lista, ou insira um novo procedimento clicando no sinal de +', on_delete=models.CASCADE) # Procedimentos padronizados a partir da tabela de preços
	dente = models.CharField(max_length = 20, blank = True, help_text='Registre qual o dente tratado')
	descr_anterior = models.CharField(max_length = 200, blank=True, verbose_name="Descrição do procedimento", help_text = 'Descrição anterior do procedimento (Opcional)')
	valor_real = models.FloatField(blank=True, null=True, verbose_name = 'Valor')
	valor_liquido_recebido = models.FloatField(blank=True, null=True, verbose_name = 'Valor líquido efetivamente recebido')
	valor_repassado = models.FloatField(blank=True, null=True, verbose_name = 'Valor repassado ao dentista')
	recebido = models.BooleanField(blank=True, default=False)
	glosado = models.BooleanField(blank=True, default=False)
	motivo_glosa = models.CharField(max_length = 200, blank=True, verbose_name = 'Motivo da glosa')
	data_recebimento = models.DateField(blank=True, null=True, verbose_name = 'Data de recebimento')
	data_repasse = models.DateField(blank=True, null=True, verbose_name = 'Data de repasse')
	repassado = models.BooleanField(blank=True, default=False)
	#	desconto = models.FloatField(blank=True, null = True)

	def get_absolute_url(self):
		return reverse('procedimentos_aplicado_list', kwargs={'pk': self.pk})

	def __str__(self):
		procedimento = self.procedimento
		valor_real = self.valor_real
		nome_procedimento = procedimento.procedimento + "/ " + str(valor_real)
		return nome_procedimento

#	def num_GTO(self):
#		atendimento = Atendimento_procedimentos_aplicados.atendimento
#		num_GTO = atendimento.
#		return

#	class Meta:
#		ordering = ['procedimento']


	def valor_liquido(self): 		#Esse código pode melhorar, fazendo um loop sobre os elementos da tabela Formas_pagamento

		if self.valor_real != None:

			particular = Convenio.objects.filter(convenio="Particular")[0]
			credito = Formas_pagamento.objects.filter(forma_pagamento="Cartão de crédito a vista")[0]
			credito_2_6_formas = (
				"Cartão de crédito 2 parcelas",
				"Cartão de crédito 3 parcelas",
				"Cartão de crédito 4 parcelas",
				"Cartão de crédito 5 parcelas",
				"Cartão de crédito 6 parcelas",
			)
			credito_2_6 = Formas_pagamento.objects.filter(forma_pagamento__in = credito_2_6_formas)[0]
			credito_7_12_formas = (
				"Cartão de crédito 7 parcelas",
				"Cartão de crédito 8 parcelas",
				"Cartão de crédito 9 parcelas",
				"Cartão de crédito 10 parcelas",
				"Cartão de crédito 11 parcelas",
				"Cartão de crédito 12 parcelas",
			)
			credito_7_12 = Formas_pagamento.objects.filter(forma_pagamento__in = credito_7_12_formas)[0]
			debito = Formas_pagamento.objects.filter(forma_pagamento="Cartão de débito")[0]
			boleto = Formas_pagamento.objects.filter(forma_pagamento="Boleto bancário")[0]
			repasse_convenio = Formas_pagamento.objects.filter(forma_pagamento="Repasse do convênio")[0]

            # Regra de negócios geral pacientes particulares pagamentos em cartão de crédito
			if self.atendimento.convenio == particular and self.atendimento.forma_pagamento == credito:
				valor_liquido = self.valor_real * (1-credito.comissao/100)
			# Regra de negócios geral pacientes particulares pagamentos em cartão de crédito 2-6 parcelas
			elif self.atendimento.convenio == particular and self.atendimento.forma_pagamento == credito_2_6:
				valor_liquido = self.valor_real * (1-credito_2_6.comissao/100)
			# Regra de negócios geral pacientes particulares pagamentos em cartão de crédito 7-12 parcelas
			elif self.atendimento.convenio == particular and self.atendimento.forma_pagamento == credito_7_12:
				valor_liquido = self.valor_real * (1-credito_7_12.comissao/100)
			# Regra de negócios geral pacientes particulares pagamentos em cartão de débito
			elif self.atendimento.convenio == particular and self.atendimento.forma_pagamento == debito:
				valor_liquido = self.valor_real * (1-debito.comissao/100)
			# Regra de negócios geral pacientes particulares pagamentos em boleto bancário

Alisystem/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Alisystem foi desenvolvido pela lucido strategy*tech.</p>

{% endblock %}

Alisystem/templates/app/atendimento_list.html
{% extends "app/layout.html" %}



{% block content %}

<div class="jumbotron">
    <h2>Atendimentos</h2>
    <p>Clique no número de cada atendimento para visualizar os procedimentos aplicados</p>
</div>

	<ul>
		<table id="atendimento_list" class="table table-bordered table-striped">
			<thead>
			<tr>
				<th>Cód.</th>
				<th>Número da GTO</th>
                <th>Data de atendimento</th>
				<th>Paciente</th>
				<th>Dentista</th>
				<th>Convênio</th>


			</tr>
			</thead>

			<tbody>

				{% for atendimento in object_list %}

			<tr>
				<td><a href="{{ atendimento.id }}/"> {{ atendimento.id }} </a></td>
				<td>{{ atendimento.num_GTO }}</td>
                <td>{{ atendimento.data_atendimento }}</td>
				<td>{{ atendimento.paciente }}</td>
				<td>{{ atendimento.dentista }}</td>
				<td>{{ atendimento.convenio }}</td>


			</tr>
				{% endfor %}

			</tbody>

			</table>

	</ul>

<!--
<form method="get" action="http://127.0.0.1:8000">
			<button type="submit">Principal</button>
</form>-->

<a href="{% url 'dentistas' %}" class="btn btn-primary btn-large">&laquo; Painel dentistas</a>
<a href="{% url 'inserir_atendimentos' %}" class="btn btn-primary btn-large">Novo atendimento &raquo;</a>
<br><br>
<a href="{% url 'home' %}" class="btn btn-primary btn-large">Home &raquo;</a>

{% endblock %}

{% load static %}

{% block scripts %}
<!-- ./wrapper -->

<!-- src="{% static "app/lucido_logo.png" %}"  -->

<!-- jQuery 3 -->
<script src="{% static "app/bower_components/jquery/dist/jquery.min.js" %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static "app/bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
<!-- DataTables -->
<script src="{% static "app/bower_components/datatables.net/js/jquery.dataTables.min.js" %}"></script>
<script src="{% static "app/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
<!-- SlimScroll -->
<script src="{% static "app/bower_components/jquery-slimscroll/jquery.slimscroll.min.js" %}"></script>
<!-- FastClick -->
<script src="{% static "app/bower_components/fastclick/lib/fastclick.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "app/dist/js/adminlte.min.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "app/dist/js/demo.js" %}"></script>
<!-- page script -->

<script>
  $(function () {

	$('#atendimento_list').DataTable()

	// Versão com paginação, ordenação e info
	// Se o id não existe, a função não é aplicada
    $('#atendimento_list1').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

{% endblock %}

Alisystem/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<h3>{{ message }}</h3>

<address>
    Rua Comendador Araujo, 510 - Cj 1603<br />
    Curitiba (PR)<br />
    <abbr title="Phone">Fone: </abbr>
    (41)3324-7272
</address>

<address>
    <strong>E-mail:</strong>   <a href="mailto:clarisodontologia@gmail.com">clarisodontologia@gmail.com</a><br />
    
</address>

{% endblock %}

Alisystem/templates/app/convenio_detail.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">

<h2>Detalhe do Convênio</h2>





<p>
<a href="add" class="btn btn-primary btn-large">Novo Convênio &raquo;</a>
</p>

</div>	
	<ul>	
		<table>
			<tr>
				<th>Cód.</th>
				<th>Convênio</th>				
			</tr>
			
				{% for convenio in object_list %}
				
			<tr>
				<td>{{ convenio.id }}</td>
				<td>{{ convenio.convenio }}</td>				
			</tr>
				{% endfor %}
			  
			</table>
		
	</ul>


<form method="get" action="http://127.0.0.1:8000">
			<button type="submit">Principal</button>
</form>


	
	
	
{% endblock %}

Alisystem/templates/app/data_repasse.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <p>{{ hora_atual }}</p>
    <h1>Alisystem</h1>
    <p class="lead">Você está prestes a atribuir ({{ data_repasse }}) como uma nova data de repasse. Clique abaixo para confirmar.</p>

    <p>
    	<a href="confirma" class="btn btn-primary btn-large">Clique para definir {{ data_repasse }} como nova data de repasse &raquo;</a>
    </p>


</div>



{% endblock %}

Alisystem/templates/app/data_repasse_confirma.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <p>{{ hora_atual }}</p>
    <h1>Alisystem</h1>
    <p class="lead">Você atribuiu a data de hoje <i><u>({{ data_repasse }})</u></i> como uma nova data de repasse</p>
    <p>
        <a href="atualiza" class="btn btn-primary btn-large">Clique para calcular o valor líquido recebido e o valor repassado &raquo;</a>
    </p>
</div>
     <p class="lead">Hoje você alterou {{ num }} procedimentos aplicados:</p>


<div>
    <table class="table table-condensed">
                <tr>
                    <th>Cód.</th>
                    <th>Núm. GTO</th>
                    <th>Convênio</th>
                    <th>Paciente</th>
                    <th>Dentista</th>
                    <th>Valor (R$)</th>
                    <th>Valor líquido (R$)</th>
                    <th>Valor repassado (R$)</th>

                </tr>

               {% for procedimento_aplicado in b  %}

                <tr>
                    <td>{{ procedimento_aplicado.atendimento.id }}</td>
                    <td>{{ procedimento_aplicado.atendimento.num_GTO }}</td>
                    <td>{{ procedimento_aplicado.atendimento.convenio }}</td>
                    <td>{{ procedimento_aplicado.atendimento.paciente }}</td>
                    <td>{{ procedimento_aplicado.atendimento.dentista }}</td>
                    <td>{{ procedimento_aplicado.valor_real }}</td>
                    <td>{{ procedimento_aplicado.valor_liquido_recebido }}</td>
                    <td>{{ procedimento_aplicado.valor_repassado }}</td>
                </tr>

        {% endfor %}

    </table>
</div>

<br>
<a class="btn btn-primary" href="/pagamentos">Retornar ao menu pagamentos &raquo;</a>

{% endblock %}

Alisystem/templates/app/dentista_list.html
 {% extends "app/layout.html" %}

{% block content %}
	<h2>Painel dos Dentistas</h2>
    <p>Clique nos botões abaixo para ver, para cada dentista, os
        <button class="btn btn-xs btn-primary">atendimentos</button>
        , os
        <button class="btn btn-xs btn-success">procedimentos repassados neste mês</button>
        e os
        <button class="btn btn-xs btn-danger">procedimentos glosados</button> .

    </p>
    <br>

	<ul>
		<table class="table table-responsive">
			<tr>
				<th>Cód.</th>
				<th>Dentista</th>
                <th>Ver todos os atendimentos do dentista</th>
                <th>Ver procedimentos repassados neste mês</th>
                <th>Ver procedimentos glosados</th>


			</tr>

				{% for dentista in object_list %}
    				{% if dentista.nome_completo == user.username or user.username == 'leonardo' or user.username == 'Alicia' or user.username == 'Josi' %}

            			<tr>
                            <td> {{ dentista.id }}</td>
            				<td> {{ dentista.nome_completo }}</a></td>
                            <td><a href="/atendimentos/dentista/{{ dentista.nome_completo }}" class="btn btn-xs btn-primary">Todos os atendimentos</a></td>
                            <td><a href="/procedimentos/dentista/{{ dentista.nome_completo }}" class="btn btn-xs btn-success">Procedimentos repassados neste mês</a></td>
                            <td><a href="/procedimentos/dentista/{{ dentista.nome_completo }}/glosado" class="btn btn-xs btn-danger">Procedimentos glosados</a></td>


            			</tr>
    				{% endif %}
				{% endfor %}

			</table>

	</ul>

<!--
<form method="get" action="http://127.0.0.1:8000">
			<button type="submit">Principal</button>
</form>-->



<a href="/admin/Alisystem/dentista/add" class="btn btn-primary btn-large">Novo dentista &raquo;</a>

<a href="{% url 'home' %}" class="btn btn-primary btn-large">Home &raquo;</a>


{% endblock %}

Alisystem/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Alisystem</h1>
    <p class="lead">Sistema de gestão para a Claris Odontologia.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Saiba mais &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Iniciando</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://www.uol.com.br">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Obtenha mais bibliotecas</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.python.org/pypi">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>MS Azure</h2>
        <p>You can easily publish to Microsoft Azure using Python Tools for Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

Alisystem/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Acesse o sistema com a sua conta.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Usuário</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Senha</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Por favor insira um nome de usuário e senha correta.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

Alisystem/templates/app/painel_dentistas.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    
    <h1>Painel dos dentistas</h1>
    
    <p class="lead">Clique abaixo para ver o painel de repasses de {{ escolha }}</p>
    
<!--    
    <p class="lead">Escolha abaixo a data de repasse</p>
    
	
    <table>{{ form.as_table }}</table>
-->
    
    <p>
    	<a href="/painel/{{ escolha }}" class="btn btn-primary btn-large">Todos os atendimentos &raquo;</a>
    	<a href="/painel/data/{{ escolha }}" class="btn btn-primary btn-large">Repasses mês atual &raquo;</a>
    	<a href="/painel/glosado/{{ escolha }}" class="btn btn-primary btn-large">Glosados &raquo;</a>
       	
    </p>
</div>

<a href="{% url 'home' %}" class="btn btn-primary btn-large">Home &raquo;</a>


{% endblock %}

Alisystem/templates/app/procedimentos_por_atendimento.html
 {% extends "app/layout.html" %} 

{% block content %} 
	
<div class = "jumbotron">
    <h2>Detalhes deste atendimento</h2>
</div>	
    <p><b>Núm. GTO:</b> {{ atendimento.num_GTO }}</p>
    <p><b>Dentista:</b> Dr(a) {{ atendimento.dentista }}</p> 
    <p><b>Convênio:</b> {{ atendimento.convenio }}</p>
    <p><b>Forma de pagamento:</b> {{ atendimento.forma_pagamento }}</p>
    <p><b>Data:</b> {{ atendimento.data_atendimento }}</p>
	<p><b>Paciente:</b> {{ atendimento.paciente }}</p>
    <p><b>Encaminhado por:</b> {{ atendimento.encaminhado_por }}</p>
    <p><b>Comentários:</b> {{ atendimento.comentarios }}</p>
	
	<br>

    <h4>Procedimentos aplicados nesta GTO</h4>
	<ul>	
		<table class="table table-condensed">
			<tr>
				<th>Cód.</th>
				<th>Procedimento</th>
				<th>Valor (R$)</th>
				<th>Repassado</th>
				<th>Glosado</th>
				
				
			</tr>
			
				{% for procedimento in atendimento.procedimentos_aplicado_set.all %}
				
			<tr>
				<td>{{ procedimento.id }}</td>
				<td>{{ procedimento.procedimento }}</td>
				<td>{{ procedimento.valor_real }}</td>
				<td>{% if procedimento.repassado %} &#10004;&#128512;&#128514; {% else %}  {% endif %}</td>
				<td>{% if procedimento.glosado %} Glosado!&#128530;  {% else %}  {% endif %}</td>
				
				
			</tr>
				{% endfor %}
			  
			</table>
			
			<p></p>
		
	</ul>

<!--	
<form method="get" action="http://127.0.0.1:8000">
			<button type="submit">Principal</button>
</form>-->

<p><a href="/atendimentos/dentista/{{ atendimento.dentista }}" class="btn btn-primary btn-large">&laquo; Voltar para os atendimentos deste dentista</a></p>
<a href="/atendimentos/" class="btn btn-primary btn-large">&laquo; Voltar para todos os atendimentos</a>


	
	
{% endblock %} 